// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehdmyhvcrpzdzvhgzemw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoZG15aHZjcnB6ZHp2aGd6ZW13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2Mjc3NzksImV4cCI6MjA1NzIwMzc3OX0.uUP--0VuIE8vWLwh11PLEmyBYG8p_8owPftPiGNLzMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);